//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppDBEntities : DbContext
    {
        public AppDBEntities()
            : base("name=AppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<Casting> Castings { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Distribution> Distributions { get; set; }
        public virtual DbSet<Distributor> Distributors { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<ResetPasswordCommand> ResetPasswordCommands { get; set; }
        public virtual DbSet<UnverifiedEmail> UnverifiedEmails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
